// Code generated by goctl. DO NOT EDIT.
package types

type UserCreateReq struct {
	Name     string `json:"name"`
	Nickname string `json:"nickname"`
}

type UserCreateResp struct {
	Flag bool `json:"flag"`
}

type UserInfoReq struct {
	UserId int64 `path:"userId"` // 这是路径参数
}

type UserInfoResp struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
}

type UserInfoUpdateReq struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
}

type UserInfoUpdateResp struct {
	Flag bool `json:"flag"`
}
